/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author abighail
 */
public class Form extends javax.swing.JInternalFrame {
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        
        Koneksi koneksi = new Koneksi();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMerk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPlat = new javax.swing.JTextField();
        txtWarna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 454));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Merk");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 54, -1, -1));

        txtMerk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Plat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtPlat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlatActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));

        txtWarna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Warna");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Jenis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        cbJenis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Balap", "Sport", "Truk" }));
        getContentPane().add(cbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 100, -1));

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 90, 35));

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 90, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMerk.setEditable(true);
        txtMerk.setText(null);
        txtPlat.setText(null);
        txtWarna.setText(null);
        cbJenis.setSelectedItem(this);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtMerk.getText().isEmpty() || txtPlat.getText().isEmpty() || txtWarna.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data belum terisi.");
        }else{
            try{
                String query = "INSERT into mobil (Merk,Plat,Warna,Jenis) VALUES ('"+txtMerk.getText()+"','"+txtPlat.getText()+"','"+txtWarna.getText()+"','"+cbJenis.getSelectedItem()+"')";
                java.sql.Connection koneksi = (Connection)Koneksi.getKoneksi();
                java.sql.PreparedStatement stmt = koneksi.prepareStatement(query);
                int success = stmt.executeUpdate(query);
                if(success == 1){
                    JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan.");
                }else{
                    JOptionPane.showMessageDialog(null, "Data gagal ditambahkan.");
                }
                
                txtMerk.setEditable(true);
                txtMerk.setText(null);
                txtPlat.setText(null);
                txtWarna.setText(null);
                cbJenis.setSelectedItem(this);
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        } 
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtPlat;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
