/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2;

import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abighail
 */
public class Table extends javax.swing.JInternalFrame {
    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
        Koneksi koneksi = new Koneksi();
        tampil_data();
    }
    
    private DefaultTableModel model;
  
    private void tampil_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Merk");
        model.addColumn("Plat");
        model.addColumn("Warna");
        model.addColumn("Jenis");
             
        try{
            int no = 1;
            String query = "SELECT * FROM mobil";
            java.sql.Connection koneksi = (Connection)Koneksi.getKoneksi();
            java.sql.Statement stmt = koneksi.createStatement();
            java.sql.ResultSet result = stmt.executeQuery(query);
            
            while (result.next()){
                //ngambil dari database
                String merk     = result.getString("Merk");
                String plat     = result.getString("Plat");                
                String warna    = result.getString("Warna");
                String jenis    = result.getString("Jenis");
                
                model.addRow(new Object[]{no++,merk, plat, warna, jenis});
            }
        }catch(Exception e){
            System.out.println("Error : " + e.getMessage());
        }
        
        tblMobil.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMobil = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 454));

        tblMobil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Merk", "Plat", "Warna", "Jenis"
            }
        ));
        jScrollPane1.setViewportView(tblMobil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMobil;
    // End of variables declaration//GEN-END:variables
}
